[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   server role = standalone server
   security = user

   passdb backend = smbpasswd
   smb passwd file = /etc/samba/smbpasswd

   map to guest = Never
   guest ok = no
   usershare allow guests = no

   server min protocol = SMB2
   client min protocol = SMB2
   ntlm auth = yes

   smb ports = 445
   disable netbios = yes

   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

   access based share enum = yes
   hide unreadable = yes

   logging = syslog@1 file@0
   log level = 0

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes
   valid users = member contributor librarian
   write list = librarian
   create mask = 0664
   directory mask = 0775
   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = yes
   valid users = @readonly @staff
   write list = @staff
   create mask = 0664
   directory mask = 0775
   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = yes
   valid users = @readonly @staff
   write list = @staff
   create mask = 0664
   directory mask = 0775
   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[sourcecode]
   path = /libraryit/sourcecode
   browseable = yes
   read only = no
   valid users = @staff
   create mask = 0664
   directory mask = 0770
   vfs objects = full_audit
   full_audit:prefix = %u|%S
   full_audit:success = all
   full_audit:failure = all
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE
